### ISSUE TITLE
파일 저장 문제

### ISSUE THREAD

**Issue by minyoung347** [lumyjuwon/KoreaNewsCrawler#7]
writer.py로 깔끔하게 정리된 것 같습니다. 그런데 리눅스에서 파일에 저장하고 닫을 때, close 부분에 문제가 있는 것 같습니다. 혹시 윈도우에서는 문제가 없으신가요?

{'start_year': 2000, 'start_month': 1, 'end_year': 2000, 'end_month': 2}
IT과학 PID: 24333
IT과학 Urls are generated
The crawler starts
Process Process-1:
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/my/anaconda3/envs/env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "articlecrawler.py", line 158, in crawling
    writer_csv.close()
AttributeError: '_csv.writer' object has no attribute 'close'

**Comment by lumyjuwon** [comment]
아 확인해보니 writer_wcsv = Writer().get_wcsv()이라 코드를 작성했었네요.
wcsv 객체는 close 메서드가 없고 Writer객체가 close 메서드가 있는데 잠시 착오로 인해
writer_wcsv에서 close 메서드를 호출해서 발생한 오류였습니다.
본 내용은 수정해서 1.30 버전으로 다시 커밋 해뒀습니다.
감사합니다 ^^

**Comment by minyoung347** [comment]
확인해주셔서 감사합니다 :)
